import pandas as pd

print("=" * 60)
print("1. CONNECTION.PARQUET - Данные о подключениях")
print("=" * 60)
df_conn = pd.read_parquet('connection.parquet')
print(f"Размер: {df_conn.shape[0]} строк, {df_conn.shape[1]} колонок")
print("\nКолонки:")
for col in df_conn.columns:
    print(f"  - {col}")
print("\nПервые 3 строки:")
print(df_conn.head(3))
print("\nТипы данных:")
print(df_conn.dtypes)

print("\n" + "=" * 60)
print("2. CONSUMPTION.PARQUET - Данные о потреблении")
print("=" * 60)
df_cons = pd.read_parquet('consumption.parquet')
print(f"Размер: {df_cons.shape[0]} строк, {df_cons.shape[1]} колонок")
print("\nКолонки:")
for col in df_cons.columns:
    print(f"  - {col}")
print("\nПервые 3 строки:")
print(df_cons.head(3))
print("\nТипы данных:")
print(df_cons.dtypes)

print("\n" + "=" * 60)
print("3. MARKET_ACCESS.PARQUET - Данные о доступе к рынку")
print("=" * 60)
df_market = pd.read_parquet('market_access.parquet')
print(f"Размер: {df_market.shape[0]} строк, {df_market.shape[1]} колонок")
print("\nКолонки:")
for col in df_market.columns:
    print(f"  - {col}")
print("\nПервые 3 строки:")
print(df_market.head(3))
print("\nТипы данных:")
print(df_market.dtypes)
